version: '3'

volumes:
  prometheus_data:

services:

  flipt:
    container_name: flipt
    image: flipt/flipt:v1.28.0
    command:
      - /flipt
      - --config=/etc/flipt/config.yml
    ports:
      - 8080:8080  # REST API and web UI
      - 9000:9000  # GRPC
    volumes:
      - ./flipt:/etc/flipt

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
